### ISSUE TITLE
Composer packaging?

### ISSUE THREAD

**Issue by cviebrock** [mediaburst/clockwork-php#1]
Looks great! Any chance of re-working your code slightly to make incorporating it into [Composer](http://getcomposer.corg)-managed projects easier? (i.e. `composer.json` file, namespacing and PSR-0 class names)?

**Comment by martinsteel** [comment]
Haven't forgotten about this but it's still on hold as it breaks WordPress (a significant number of our users) - hopefully they'll drop PHP 5.2 support soon and we can move with the times.

**Comment by develerltd** [comment]
Any update on this? It would be very useful to be able to use composer and namespace this
