### ISSUE TITLE
Laravel 5

### ISSUE THREAD

**Issue by sdeering** [mediaburst/clockwork-php#5]
Hi guys, have you got any documentation on how to integrate Clockwork with L5?

**Comment by martinsteel** [comment]
Unfortunately none of us have used Lavarel, we're primarily a .NET shop and generally only use PHP with WordPress.

**Comment by sdeering** [comment]
oh ok, so other companies code the plugins for PHP?

**Comment by martinsteel** [comment]
We maintain the PHP wrapper but it's just vanilla PHP so it can be used with any framework. 

The only product we have experience of using it with is WordPress.

**Comment by sdeering** [comment]
Ok thanks mate.
