### ISSUE TITLE
HTTP Error calling Clockwork API - HTTP Status: 0 - cURL Erorr: SSL certificate problem: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by sdeering** [mediaburst/clockwork-php#6]
Any ideas?

![image](https://cloud.githubusercontent.com/assets/1787454/8445788/e26b3140-1fe4-11e5-8d41-008b8045e358.png)

**Comment by martinsteel** [comment]
It looks like your PHP setup is missing its root certificates, take a look at our readme for some hints:
https://github.com/mediaburst/clockwork-php#ssl-errors

**Comment by sdeering** [comment]
Yeah I solved this one. Just to help others if your working locally you can add this to your php.ini

```
[certs]
curl.cainfo = "<path to>/cacert.pem"
```
